
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

android.useAndroidX=true

reactNativeArchitectures=arm64-v8a
newArchEnabled=true
#newArchEnabled= true #// fastopening i use it false true
# If you are using Vision Camera 4+
unstable_visionCameraV4=true

hermesEnabled=true
reanimated.skipMinimalReactNativeVersionCheck=true
MYAPP_RELEASE_STORE_FILE=my-release-key.keystore
MYAPP_RELEASE_KEY_ALIAS=my-key-alias
MYAPP_RELEASE_STORE_PASSWORD=99979300
MYAPP_RELEASE_KEY_PASSWORD=99979300

android.ndk.suppressMinSdkVersionError=24
android.ndkVersion=27.1.12297006
android.extractNativeDebugSymbolLevel=SYMBOL_TABLE
# Replace with the path you got from 'which npx'
org.gradle.project.react.npxCommand=C:\\Program Files\\nodejs\\npx.cmd

# This helps libraries find CMake
android.defaults.buildfeatures.buildconfig=true
# Enable the new Prefab system required for Skia
android.prefabEnabled=true
REANIMATED_SKIP_VERIFY_RN_VERSION=true
org.gradle.parallel=true
org.gradle.workers.max=2

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.configuration-cache=false
#org.gradle.caching=true #// opening faster
#org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g #//opening faster
# This is crucial for newer AGP versions
android.nonTransitiveRClass=false
android.enableJetifier=true

systemProp.javax.net.ssl.trustStoreType=Windows-ROOT

org.gradle.java.home=C:\\Users\\Waleed\\.gradle\\jdks\\eclipse_adoptium-17-amd64-windows.2